### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-xyz-tiles#10]
```
Traceback (most recent call last):
File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tiles_xyz\tiles_xyz_algorithm.py", line 384, in processAlgorithm
self.generate(writer, parameters, context, feedback)
File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tiles_xyz\tiles_xyz_algorithm.py", line 260, in generate
writer.write_tile(tile, tile_img)
File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tiles_xyz\tiles_xyz_algorithm.py", line 339, in write_tile
self._init_zoom_layer(tile.z)
File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tiles_xyz\tiles_xyz_algorithm.py", line 331, in _init_zoom_layer
self._execute_sqlite("UPDATE metadata SET value='{}' WHERE name='bounds'".format(bounds))
File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tiles_xyz\tiles_xyz_algorithm.py", line 312, in _execute_sqlite
conn.execute(cmd)
sqlite3.OperationalError: database is locked
```

**Comment by saberraz** [comment]
Traceback (most recent call last):
```
File "C:/Users/Saber/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tiles_xyz\tiles_xyz_algorithm.py", line 386, in processAlgorithm
self.generate(writer, parameters, context, feedback)
File "C:/Users/Saber/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tiles_xyz\tiles_xyz_algorithm.py", line 262, in generate
writer.write_tile(tile, tile_img)
File "C:/Users/Saber/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tiles_xyz\tiles_xyz_algorithm.py", line 341, in write_tile
self._init_zoom_layer(tile.z)
File "C:/Users/Saber/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tiles_xyz\tiles_xyz_algorithm.py", line 333, in _init_zoom_layer
self._execute_sqlite("UPDATE metadata SET value='{}' WHERE name='bounds'".format(bounds))
File "C:/Users/Saber/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tiles_xyz\tiles_xyz_algorithm.py", line 314, in _execute_sqlite
conn.execute(cmd)
sqlite3.OperationalError: database is locked

```
Execution failed after 75.04 seconds
