### ISSUE TITLE
Import error!

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-xyz-tiles#25]
https://twitter.com/carlosgis/status/1140999359724761094
![D9Wk2f6XUAUE1zi](https://user-images.githubusercontent.com/2649047/59703773-8d491180-91f2-11e9-9840-3862791b55d8.jpg)

**Comment by DigDigDig** [comment]
I'm getting the same issue here.  Were you able to resolve this?

**Comment by saberraz** [comment]
Have you tried QGIS 3.8 ...no plugin needed and you should be able to run it directly from the processing toolbox.

**Comment by fnx2k** [comment]
Same issue with QGIS 3.4.6 LTR: 
Is there any bypass ?
 I am not really fan of upgrading to 3.8 right now, in the middle of a project ...

> **Impossible` de charger l'extension 'tiles_xyz** 
> 
> **ImportError: attempted relative import with no known parent package** 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 309, in loadPlugin
>     __import__(packageName)
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/home/xxx/.local/share/QGIS/QGIS3/profiles/default/python/plugins/tiles_xyz/tiles_xyz.py", line 38, in 
>     from .tiles_xyz_provider import TilesXYZProvider
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
> ImportError: attempted relative import with no known parent package
> 
> 
> Version de Python : 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] 
> Version de QGIS : 3.4.6-Madeira Madeira, exported 
>
