### ISSUE TITLE
"sqlite3.OperationalError: database is locked"

### ISSUE THREAD

**Issue by kannes** [lutraconsulting/qgis-xyz-tiles#9]
QGIS version | 3.6.1-Noosa
Plugin installed just now.

```
Processing algorithm…
Algorithm 'Generate XYZ tiles (MBTiles)' starting…
Input parameters:
{ 'DPI' : 150, 'EXTENT' : '532566.3961918731,604272.4545227268,5911272.408939038,5965051.952687179 [EPSG:25832]', 'OUTPUT_FILE' : '/home/test/test.mbtiles', 'TILE_FORMAT' : 0, 'ZOOM_MAX' : 16, 'ZOOM_MIN' : 1 }

Generating tiles for zoom level: 1
Generating tiles for zoom level: 2
Generating tiles for zoom level: 3
Generating tiles for zoom level: 4
Generating tiles for zoom level: 5
Generating tiles for zoom level: 6
Generating tiles for zoom level: 7
Generating tiles for zoom level: 8
Generating tiles for zoom level: 9
Generating tiles for zoom level: 10
Generating tiles for zoom level: 11
Generating tiles for zoom level: 12
Generating tiles for zoom level: 13
Generating tiles for zoom level: 14
Generating tiles for zoom level: 15
Traceback (most recent call last):
File "/home/me/.local/share/QGIS/QGIS3/profiles/default/python/plugins/tiles_xyz/tiles_xyz_algorithm.py", line 384, in processAlgorithm
self.generate(writer, parameters, context, feedback)
File "/home/me/.local/share/QGIS/QGIS3/profiles/default/python/plugins/tiles_xyz/tiles_xyz_algorithm.py", line 260, in generate
writer.write_tile(tile, tile_img)
File "/home/me/.local/share/QGIS/QGIS3/profiles/default/python/plugins/tiles_xyz/tiles_xyz_algorithm.py", line 339, in write_tile
self._init_zoom_layer(tile.z)
File "/home/me/.local/share/QGIS/QGIS3/profiles/default/python/plugins/tiles_xyz/tiles_xyz_algorithm.py", line 331, in _init_zoom_layer
self._execute_sqlite("UPDATE metadata SET value='{}' WHERE name='bounds'".format(bounds))
File "/home/me/.local/share/QGIS/QGIS3/profiles/default/python/plugins/tiles_xyz/tiles_xyz_algorithm.py", line 312, in _execute_sqlite
conn.execute(cmd)
sqlite3.OperationalError: database is locked

Execution failed after 39.49 seconds

Loading resulting layers
Algorithm 'Generate XYZ tiles (MBTiles)' finished
```

**Comment by saberraz** [comment]
see #12
